# Generated by Django 2.1.1 on 2019-01-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_Name', models.CharField(max_length=30)),
                ('last_Name', models.CharField(max_length=30)),
                ('streetAdd', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=10)),
                ('zipNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
